question_data_other = [
    {"type": "boolean",
     "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "According to scholarly estimates, what percentage of the world population at the time died due to Tamerlane&#039;s conquests?",
     "correct_answer": "5%", "incorrect_answers": ["1%", "3%", "&lt;1%"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "What was the name of the device used by Scarecrow in Batman: Arkham Knight to cover Gotham in fear gas?",
     "correct_answer": "The Cloudburst",
     "incorrect_answers": ["The Fear Bomb", "The Fearburst", "Cloud Dispersal System"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science &amp; Nature",
     "question": "Which of the following liquids is least viscous? Assume temperature is 25&deg;C.",
     "correct_answer": "Acetone", "incorrect_answers": ["Water", "Mercury", "Benzene"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Books",
     "question": "Who wrote &quot;Harry Potter&quot;?", "correct_answer": "J.K. Rowling",
     "incorrect_answers": ["J.R.R. Tolkien", "Terry Pratchett", "Daniel Radcliffe"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Which of these Marvel games was released on the Playstation 2?", "correct_answer": "Spider-Man 2",
     "incorrect_answers": ["Silver Surfer", "Howard the Duck", "Wolverine: Adamantium Rage"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "What alcoholic drink is mainly made from juniper berries?", "correct_answer": "Gin",
     "incorrect_answers": ["Vodka", "Rum", "Tequila"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "How many classes are there in Team Fortress 2?", "correct_answer": "9",
     "incorrect_answers": ["10", "8", "7"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Television",
     "question": "In 2008, British celebrity chef Gordon Ramsay believes he almost died after suffering what accident in Iceland while filming?",
     "correct_answer": "Slipping off a cliff, and nearly drowning in icy water",
     "incorrect_answers": ["Crash landing when arriving at Keflav&iacute;k airport",
                           "A minor car accident in a snowstorm", "Being served under-cooked chicken at his hotel"]}
]

question_data = [
    {"text": "O Brasil é o maior país da América do Sul.", "answer": "Verdade"},
    {"text": "A capital do Brasil já foi Salvador.", "answer": "Verdade"},
    {"text": "O Rio de Janeiro é a capital atual do Brasil.", "answer": "Falso"},
    {"text": "A feijoada é considerada um prato típico brasileiro.", "answer": "Verdade"},
    {"text": "O Guaraná é originário do Sudeste brasileiro.", "answer": "Falso"},
    {"text": "Pelé marcou mais de mil gols em sua carreira.", "answer": "Verdade"},
    {"text": "A seleção brasileira de futebol tem cinco títulos de Copa do Mundo.",
        "answer": "Verdade"},
    {"text": "A moeda do Brasil atual é o Cruzeiro.", "answer": "Falso"},
    {"text": "O maior bioma do Brasil é a Amazônia.", "answer": "Verdade"},
    {"text": "O cerrado ocupa mais área que a Caatinga.", "answer": "Verdade"},
    {"text": "O Brasil foi colonizado pela Espanha.", "answer": "Falso"},
    {"text": "A independência do Brasil ocorreu em 1822.", "answer": "Verdade"},
    {"text": "O Brasil já teve uma mulher presidenta da República.", "answer": "Verdade"},
    {"text": "Brasília foi inaugurada em 1960.", "answer": "Verdade"},
    {"text": "Chico Buarque é conhecido apenas como ator.", "answer": "Falso"},
    {"text": "A Festa de Parintins acontece no Amazonas.", "answer": "Verdade"},
    {"text": "O chimarrão é uma tradição típica do Nordeste brasileiro.", "answer": "Falso"},
    {"text": "O Cristo Redentor é uma das sete maravilhas do mundo moderno.",
        "answer": "Verdade"},
    {"text": "O frevo é um ritmo tradicional de Pernambuco.", "answer": "Verdade"},
    {"text": "Sandy e Júnior são irmãos na vida real.", "answer": "Verdade"},
    {"text": "A telenovela 'Avenida Brasil' foi exibida pela Globo.", "answer": "Verdade"},
    {"text": "A Bahia é o estado mais populoso do Brasil.", "answer": "Falso"},
    {"text": "A música 'Asa Branca' foi composta por Luiz Gonzaga.", "answer": "Verdade"},
    {"text": "O bumba meu boi é uma tradição típica do Sul do Brasil.", "answer": "Falso"},
    {"text": "O açaí é originalmente da região Norte.", "answer": "Verdade"},
    {"text": "Ronaldinho Gaúcho ganhou duas Bolas de Ouro da FIFA.", "answer": "Verdade"},
    {"text": "O SUS foi criado na Constituição de 1988.", "answer": "Verdade"},
    {"text": "A música sertaneja nasceu no estado de Roraima.", "answer": "Falso"},
    {"text": "O Rio São Francisco nasce em Minas Gerais.", "answer": "Verdade"},
    {"text": "A atriz Juliana Paes já interpretou a personagem Gabriela.",
        "answer": "Verdade"},
    {"text": "O Brasil tem 27 estados incluindo o Distrito Federal.", "answer": "Verdade"},
    {"text": "A Amazônia Legal abrange apenas o estado do Amazonas.", "answer": "Falso"},
    {"text": "O maracanã já recebeu mais de 150 mil pessoas em um jogo.",
        "answer": "Verdade"},
    {"text": "O samba nasceu no Rio Grande do Sul.", "answer": "Falso"},
    {"text": "Cazuza foi vocalista do Barão Vermelho.", "answer": "Verdade"},
    {"text": "O impeachment de Collor ocorreu em 1992.", "answer": "Verdade"},
    {"text": "A dublê de Anitta é sua irmã gêmea.", "answer": "Falso"},
    {"text": "O primeiro avião a voar foi criado por Santos Dumont.", "answer": "Verdade"},
    {"text": "O Brasil usa três fusos horários atualmente.", "answer": "Verdade"},
    {"text": "A seleção brasileira de vôlei feminino já foi campeã olímpica.",
        "answer": "Verdade"},
    {"text": "O Pantanal é o maior bioma do Brasil.", "answer": "Falso"},
    {"text": "Neymar estreou na seleção com 17 anos.", "answer": "Verdade"},
    {"text": "A festa junina é celebrada especialmente no inverno brasileiro.",
        "answer": "Verdade"},
    {"text": "O MASP fica na cidade de Recife.", "answer": "Falso"},
    {"text": "O ator Lázaro Ramos é baiano.", "answer": "Verdade"},
    {"text": "A literatura de cordel é típica do Sul do Brasil.", "answer": "Falso"},
    {"text": "O Brasil foi descoberto oficialmente em 1500.", "answer": "Verdade"},
    {"text": "Manaus fica no estado de Roraima.", "answer": "Falso"},
    {"text": "O brigadeiro foi criado no Brasil.", "answer": "Verdade"},
    {"text": "O jogador Cafu é o brasileiro que mais entrou em finais de Copa.",
        "answer": "Verdade"},
    {"text": "A maior parte do território brasileiro está no hemisfério norte.",
        "answer": "Falso"},
    {"text": "O ator Rodrigo Santoro já atuou em Hollywood.", "answer": "Verdade"},
    {"text": "A Arara Azul é encontrada apenas na Mata Atlântica.", "answer": "Falso"},
    {"text": "O estado de Goiás possui praias naturais.", "answer": "Falso"},
    {"text": "Ivete Sangalo começou sua carreira como vocalista da Banda Eva.",
        "answer": "Verdade"},
    {"text": "A maior festa de Réveillon do Brasil é em Copacabana.", "answer": "Verdade"},
    {"text": "O deputado federal é eleito para mandato de 6 anos.", "answer": "Falso"},
    {"text": "O primeiro presidente do Brasil foi Deodoro da Fonseca.", "answer": "Verdade"},
    {"text": "A novela 'O Clone' tratou de clonagem humana.", "answer": "Verdade"},
    {"text": "O carimbó é tradicional do Pará.", "answer": "Verdade"},
    {"text": "A bandeira do Brasil tem exatamente 28 estrelas.", "answer": "Falso"},
    {"text": "O Lago Paranoá fica em Brasília.", "answer": "Verdade"},
    {"text": "A atriz Taís Araújo foi a primeira protagonista negra de uma novela das 8.",
        "answer": "Verdade"},
    {"text": "A Ilha de Marajó fica na Bahia.", "answer": "Falso"},
    {"text": "A Serra Gaúcha é famosa pela produção de vinhos.", "answer": "Verdade"},
    {"text": "O piloto Ayrton Senna ganhou quatro campeonatos mundiais.", "answer": "Falso"},
    {"text": "O MST é um movimento social brasileiro.", "answer": "Verdade"},
    {"text": "A telenovela brasileira mais exportada da história é 'Senhora do Destino'.", "answer": "Falso"},
    {"text": "O cantor Belo já foi vocalista do grupo Soweto.", "answer": "Verdade"},
    {"text": "O jalapão fica no estado do Tocantins.", "answer": "Verdade"},
    {"text": "O estado de Roraima fica totalmente acima da linha do Equador.",
        "answer": "Verdade"},
    {"text": "O funk carioca nasceu na década de 90.", "answer": "Falso"},
    {"text": "A seleção brasileira masculina de basquete tem título mundial.",
        "answer": "Verdade"},
    {"text": "A cachaça é uma bebida originalmente espanhola.", "answer": "Falso"},
    {"text": "A atriz Marina Ruy Barbosa começou na TV ainda criança.", "answer": "Verdade"},
    {"text": "O rio Tietê nasce no estado do Rio de Janeiro.", "answer": "Falso"},
    {"text": "O humorista Renato Aragão é conhecido como Didi.", "answer": "Verdade"},
    {"text": "A moeda Real foi criada em 1994.", "answer": "Verdade"},
    {"text": "O cantor Leonardo fazia dupla com Zezé di Camargo.", "answer": "Falso"},
    {"text": "O impeachment de Dilma ocorreu em 2016.", "answer": "Verdade"},
    {"text": "A maior usina hidrelétrica totalmente brasileira é Itaipu.", "answer": "Falso"},
    {"text": "O Protocolo de Kyoto foi assinado no Brasil.", "answer": "Falso"},
    {"text": "O ator Bruno Gagliasso é casado com Giovanna Ewbank.", "answer": "Verdade"},
    {"text": "A Serra do Mar fica na região Norte.", "answer": "Falso"},
    {"text": "A música 'Evidências' é da dupla Chitãozinho e Xororó.", "answer": "Verdade"},
    {"text": "A Floresta Amazônica abrange nove países.", "answer": "Verdade"},
    {"text": "O surfista Gabriel Medina já foi campeão mundial.", "answer": "Verdade"},
    {"text": "O lago Titicaca fica no território brasileiro.", "answer": "Falso"},
    {"text": "Carlinhos Brown é baiano.", "answer": "Verdade"},
    {"text": "O Nordeste brasileiro possui 9 estados.", "answer": "Verdade"},
    {"text": "O ator Tony Ramos é famoso por atuar somente em filmes mudos.",
        "answer": "Falso"},
    {"text": "O politicamente conhecido Tiradentes foi enforcado.", "answer": "Verdade"},
    {"text": "O estado de São Paulo tem o maior PIB do Brasil.", "answer": "Verdade"},
    {"text": "A atriz Paolla Oliveira já venceu a Dança dos Famosos.", "answer": "Verdade"},
    {"text": "O Rio Grande do Norte é o estado mais ao sul do Brasil.", "answer": "Falso"},
    {"text": "O sambista Cartola é um dos fundadores da escola de samba Mangueira.",
        "answer": "Verdade"},
    {"text": "O Brasil possui apenas um bioma oficial reconhecido pelo IBGE.",
        "answer": "Falso"},
    {"text": "A feijoada é um prato de origem indígena.", "answer": "Falso"},
    {"text": "A Bossa Nova surgiu oficialmente no final da década de 1950.",
        "answer": "Verdade"},
    {"text": "A cidade de Olinda é famosa pelo seu Carnaval e pelos bonecos gigantes.",
        "answer": "Verdade"},
    {"text": "O escritor Graciliano Ramos escreveu 'Dom Casmurro'.", "answer": "Falso"},
    {"text": "A Amazônia é o maior bioma brasileiro em extensão territorial.",
        "answer": "Verdade"},
    {"text": "Pelé marcou mais de mil gols na carreira profissional.", "answer": "Verdade"},
    {"text": "A seleção brasileira masculina de futebol nunca venceu uma Copa América.", "answer": "Falso"},
    {"text": "A música 'Asa Branca' é de Luiz Gonzaga e Humberto Teixeira.",
        "answer": "Verdade"},
    {"text": "A primeira capital do Brasil foi a cidade de Salvador.", "answer": "Verdade"},
    {"text": "O animal símbolo do Brasil é o lobo-guará.", "answer": "Falso"},
    {"text": "Machado de Assis foi o fundador da Academia Brasileira de Letras.",
        "answer": "Verdade"},
    {"text": "A cachaça é produzida exclusivamente no Brasil.", "answer": "Verdade"},
    {"text": "O presidente Juscelino Kubitschek foi o responsável pela construção de Brasília.",
        "answer": "Verdade"},
    {"text": "O Rio São Francisco nasce no Ceará.", "answer": "Falso"},
    {"text": "O brigadeiro recebeu esse nome em homenagem a um militar brasileiro.",
        "answer": "Verdade"},
    {"text": "A telenovela 'Avenida Brasil' foi exibida pela Rede Record.", "answer": "Falso"},
    {"text": "O coco-da-baía é também conhecido como coco seco.", "answer": "Verdade"},
    {"text": "O grupo É o Tchan tinha personagens famosos como Jacaré e Compadre Washington.",
        "answer": "Verdade"},
    {"text": "A seleção feminina de vôlei do Brasil já foi campeã olímpica.",
        "answer": "Verdade"},
    {"text": "O boto-cor-de-rosa é encontrado no Pantanal.", "answer": "Falso"},
    {"text": "Caetano Veloso e Gilberto Gil participaram do movimento Tropicalista.",
        "answer": "Verdade"},
    {"text": "A ponte Rio-Niterói é oficialmente chamada de Ponte Presidente Dutra.",
        "answer": "Falso"},
    {"text": "No Brasil, a onça-pintada é o maior felino da América do Sul.",
        "answer": "Verdade"},
    {"text": "O ator Lázaro Ramos já interpretou o personagem Foguinho na novela Cobras & Lagartos.",
     "answer": "Verdade"},
    {"text": "O Rio de Janeiro sediou os Jogos Olímpicos de 2012.", "answer": "Falso"},
    {"text": "O refrigerante Guaraná Jesus é produzido no Maranhão.", "answer": "Verdade"},
    {"text": "A revista 'Caras' é uma das mais tradicionais do Brasil no segmento de celebridades.",
     "answer": "Verdade"},
    {"text": "O cantor Roberto Carlos é conhecido como o 'Rei do Rock' no Brasil.",
        "answer": "Falso"},
    {"text": "A Serra Gaúcha é famosa pela produção de vinhos.", "answer": "Verdade"},
    {"text": "O impeachement de Dilma Rousseff ocorreu em 2014.", "answer": "Falso"},
    {"text": "O açaí consumido no Norte é geralmente acompanhado de peixe e farinha.",
        "answer": "Verdade"},
    {"text": "Ivete Sangalo começou sua carreira na banda Asa de Águia.", "answer": "Falso"},
    {"text": "O vice de Jair Bolsonaro em 2018 foi Hamilton Mourão.", "answer": "Verdade"},
    {"text": "O frevo é uma dança típica do Rio Grande do Sul.", "answer": "Falso"},
    {"text": "Rita Lee é considerada a ‘Rainha do Rock Brasileiro’.", "answer": "Verdade"},
    {"text": "A moeda oficial do Brasil já foi o cruzeiro.", "answer": "Verdade"},
    {"text": "O Paraná faz fronteira com o estado de São Paulo.", "answer": "Verdade"},
    {"text": "O Brasil já teve uma princesa regente chamada Isabel.", "answer": "Verdade"},
    {"text": "O apresentador Fausto Silva estreou na TV como participante do Cassino do Chacrinha.", "answer": "Falso"},
    {"text": "A seleção brasileira venceu a Copa do Mundo de 2006.", "answer": "Falso"},
    {"text": "O Rio Negro encontra o Rio Solimões no fenômeno chamado Encontro das Águas.",
        "answer": "Verdade"},
    {"text": "A atriz Taís Araújo foi protagonista da novela Xica da Silva.",
        "answer": "Verdade"},
    {"text": "O Real foi criado no governo de Fernando Henrique Cardoso.",
        "answer": "Verdade"},
    {"text": "O Cristo Redentor foi eleito uma das Novas Sete Maravilhas do Mundo.",
        "answer": "Verdade"},
    {"text": "O cantor Chorão era vocalista da banda Jota Quest.", "answer": "Falso"},
    {"text": "A Serra do Mar está localizada majoritariamente na região Nordeste.",
        "answer": "Falso"},
    {"text": "Xuxa Meneghel já apresentou um programa infantil na Argentina.",
        "answer": "Verdade"},
    {"text": "O estado de Roraima fica no extremo sul do Brasil.", "answer": "Falso"},
    {"text": "O humorista Renato Aragão interpretava o personagem Didi Mocó.",
        "answer": "Verdade"},
    {"text": "O jogo de capoeira foi criado na China e adaptado no Brasil.",
        "answer": "Falso"},
    {"text": "Marisa Monte é uma cantora que integra o grupo Tribalistas.",
        "answer": "Verdade"},
    {"text": "O primeiro brasileiro a viajar ao espaço foi Marcos Pontes.",
        "answer": "Verdade"},
    {"text": "Chico Buarque é filho do historiador Sérgio Buarque de Holanda.",
        "answer": "Verdade"},
    {"text": "O Rio Grande do Norte é conhecido como o estado do sol nascente.",
        "answer": "Verdade"},
    {"text": "O ator Selton Mello já dirigiu filmes de cinema.", "answer": "Verdade"},
    {"text": "O Brasil nunca sediou uma Copa do Mundo.", "answer": "Falso"},
    {"text": "O cantor Leonardo fez parte do duo sertanejo Leandro & Leonardo.",
        "answer": "Verdade"},
    {"text": "A Lagoa Rodrigo de Freitas está localizada em Salvador.", "answer": "Falso"},
    {"text": "O Nordeste é a região com o maior número de estados do Brasil.",
        "answer": "Verdade"},
    {"text": "O apresentador Gugu Liberato trabalhou muitos anos no SBT.",
        "answer": "Verdade"},
    {"text": "O arroz com pequi é um prato típico da região Norte.", "answer": "Falso"},
    {"text": "A cidade de Tiradentes fica no estado de Minas Gerais.", "answer": "Verdade"},
    {"text": "O cantor Lulu Santos fez parte da banda Paralamas do Sucesso.",
        "answer": "Falso"},
    {"text": "A Praça dos Três Poderes está localizada em Brasília.", "answer": "Verdade"},
    {"text": "O humorista Whindersson Nunes nasceu em Pernambuco.", "answer": "Falso"},
    {"text": "O time do Santos revelou Pelé para o futebol mundial.", "answer": "Verdade"},
    {"text": "A cidade de Manaus está na região Centro-Oeste.", "answer": "Falso"},
    {"text": "A atriz Susana Vieira já participou de novelas desde a década de 1970.",
        "answer": "Verdade"},
    {"text": "O estado do Amazonas faz fronteira com o Uruguai.", "answer": "Falso"},
    {"text": "O cantor Zeca Pagodinho é conhecido pelo gênero samba.", "answer": "Verdade"},
    {"text": "O Brasil tem 26 estados e um Distrito Federal.", "answer": "Verdade"},
    {"text": "O ator Rodrigo Santoro já participou de filmes de Hollywood.",
        "answer": "Verdade"},
    {"text": "O Pantanal é considerado a maior planície alagável do mundo.",
        "answer": "Verdade"},
    {"text": "A telenovela 'O Clone' foi gravada em parte no Marrocos.",
        "answer": "Verdade"},
    {"text": "Getúlio Vargas foi presidente do Brasil apenas uma vez.", "answer": "Falso"},
    {"text": "O cantor Belo foi vocalista do grupo Soweto.", "answer": "Verdade"},
    {"text": "O estado de Goiás está localizado na região Sul.", "answer": "Falso"},
    {"text": "A atriz Paolla Oliveira já venceu o quadro Dança dos Famosos.",
        "answer": "Verdade"},
    {"text": "A menor unidade federativa do Brasil é Sergipe.", "answer": "Verdade"},
    {"text": "A dupla Sandy & Junior iniciou a carreira ainda na infância.",
        "answer": "Verdade"},
    {"text": "A Ilha de Marajó fica no estado do Amazonas.", "answer": "Falso"},
    {"text": "O ator Tony Ramos é conhecido por interpretar personagens com sotaques variados.",
        "answer": "Verdade"},
    {"text": "A Revolução Farroupilha ocorreu na Bahia.", "answer": "Falso"},
    {"text": "A atriz Bruno Marquezine começou a atuar ainda criança.", "answer": "Verdade"},
    {"text": "A seleção brasileira feminina de futebol nunca disputou uma final de Copa do Mundo.", "answer": "Falso"},
    {"text": "A Serra Catarinense é famosa pelas temperaturas negativas no inverno.",
        "answer": "Verdade"},
    {"text": "A atriz Claudia Raia é conhecida por seus trabalhos em musicais.",
        "answer": "Verdade"},
    {"text": "O cantor Gilberto Gil já foi Ministro da Cultura no Brasil.",
        "answer": "Verdade"},
    {"text": "A Guerra de Canudos ocorreu no estado do Maranhão.", "answer": "Falso"},
    {"text": "A maior festa junina do Brasil acontece em Campina Grande.",
        "answer": "Verdade"},
    {"text": "O estado do Acre faz fronteira com o estado do Rio Grande do Sul.",
        "answer": "Falso"},
    {"text": "O ator Wagner Moura ficou mundialmente conhecido por interpretar Pablo Escobar na série Narcos.",
     "answer": "Verdade"},
    {"text": "O rio Tietê nasce no interior de São Paulo e deságua no Oceano Atlântico.", "answer": "Falso"},
    {"text": "A seleção brasileira masculina de vôlei já foi campeã mundial.",
        "answer": "Verdade"},
    {"text": "O escritor Ariano Suassuna é autor do 'Auto da Compadecida'.",
        "answer": "Verdade"},
    {"text": "A influencer Gkay é conhecida especialmente por sua festa 'Farofa da Gkay'.",
        "answer": "Verdade"},
    {"text": "O estado de Tocantins foi criado em 1988.", "answer": "Verdade"},
    {"text": "O ator Cauã Reymond começou sua carreira como jogador de basquete.",
        "answer": "Verdade"},
    {"text": "O Rio Grande do Sul faz fronteira com o Paraguai.", "answer": "Falso"},
    {"text": "O ex-presidente Lula foi metalúrgico antes de ingressar na política.",
        "answer": "Verdade"},
    {"text": "O cantor Alok é um dos DJs brasileiros mais famosos do mundo.",
        "answer": "Verdade"},
    {"text": "O Brasil possui apenas cinco regiões oficiais: Norte, Nordeste, Sul, Sudeste e Centro-Oeste.",
     "answer": "Verdade"},
    {"text": "O ator Mateus Solano interpretou Félix na novela Amor à Vida.",
        "answer": "Verdade"},
    {"text": "O futebol foi introduzido no Brasil por Charles Miller.", "answer": "Verdade"},
    {"text": "O bioma Pantanal é conhecido como 'pulmão do mundo'.", "answer": "Falso"},
    {"text": "O Rio Araguaia é um dos principais pontos turísticos para pesca esportiva no Brasil.",
     "answer": "Verdade"},
    {"text": "A cantora brasileira Anitta já se apresentou no festival Coachella.",
        "answer": "Verdade"},
    {"text": "A cidade de São Paulo foi fundada por padres jesuítas.", "answer": "Verdade"},
    {"text": "A Serra dos Órgãos fica no estado do Paraná.", "answer": "Falso"},
    {"text": "O jogador Neymar estreou na seleção principal com apenas 18 anos.",
        "answer": "Verdade"},
    {"text": "A atriz Deborah Secco já interpretou a vilã Iris na novela 'Laços de Família'.",
        "answer": "Verdade"},
    {"text": "O brigadeiro é tradicionalmente feito com chocolate em pó, leite condensado e manteiga.",
     "answer": "Verdade"},
    {"text": "O Brasil foi descoberto oficialmente em 1500 por Pedro Álvares Cabral.",
        "answer": "Verdade"},
    {"text": "O cantor Michel Teló ficou conhecido internacionalmente com a música 'Ai Se Eu Te Pego'.",
     "answer": "Verdade"},
    {"text": "O Rio de Janeiro já foi a capital de Portugal.", "answer": "Verdade"},
    {"text": "A novela 'Pantanal' foi originalmente transmitida pela TV Globo na década de 1990.", "answer": "Falso"},
    {"text": "A onça-pintada é um animal encontrado em vários biomas do Brasil, incluindo a Amazônia e o Pantanal.",
     "answer": "Verdade"},
    {"text": "A atriz Juliana Paes interpretou a personagem Bibi Perigosa em 'A Força do Querer'.",
     "answer": "Verdade"},
    {"text": "O Guaraná é uma fruta nativa da floresta amazônica.", "answer": "Verdade"},
    {"text": "O Palácio da Alvorada é a residência oficial do Presidente da República.",
        "answer": "Verdade"},
    {"text": "A apresentadora Hebe Camargo trabalhou por muitos anos na Rede Globo.",
        "answer": "Falso"},
    {"text": "O Brasil foi tetracampeão mundial de futebol em 1994.", "answer": "Verdade"},
    {"text": "A cantora Marília Mendonça era conhecida como 'Rainha da Sofrência'.",
        "answer": "Verdade"},
    {"text": "O Pantanal está localizado exclusivamente no Brasil.", "answer": "Falso"},
    {"text": "O ator José Loreto já trabalhou como dublê antes de atuar em novelas.",
        "answer": "Verdade"},
    {"text": "A Bahia possui o maior número de municípios do Brasil.", "answer": "Verdade"},
    {"text": "A cantora Pabllo Vittar já foi indicada ao Grammy Latino.",
        "answer": "Verdade"},
    {"text": "O presidente Tancredo Neves morreu antes de tomar posse oficialmente.",
        "answer": "Verdade"},
    {"text": "O Rio Tapajós está localizado na região Sul do Brasil.", "answer": "Falso"},
    {"text": "A jogadora Marta é considerada uma das maiores atletas da história do futebol feminino.",
     "answer": "Verdade"},
    {"text": "O humorista Zé Simão é conhecido por suas participações em novelas da Globo.", "answer": "Falso"},
    {"text": "O ator Lima Duarte interpretou Zeca Diabo em 'O Bem-Amado'.",
        "answer": "Verdade"},
    {"text": "O estado de Santa Catarina fica na região Sudeste.", "answer": "Falso"},
    {"text": "A dupla sertaneja Chitãozinho & Xororó é considerada pioneira do sertanejo moderno.",
     "answer": "Verdade"},
    {"text": "O cruzeiro foi a moeda utilizada antes da introdução do real.",
        "answer": "Verdade"},
    {"text": "O cantor João Gomes é conhecido por popularizar o piseiro.",
        "answer": "Verdade"},
    {"text": "A atriz Marina Ruy Barbosa já interpretou uma personagem que pegava fogo em uma novela.",
     "answer": "Verdade"},
    {"text": "O escritor Jorge Amado nasceu na cidade de Salvador.", "answer": "Falso"},
    {"text": "O cantor Mano Brown é um dos líderes do grupo Racionais MC's.",
        "answer": "Verdade"},
    {"text": "A Serra da Canastra fica localizada na Bahia.", "answer": "Falso"},
    {"text": "A música 'Evidências' ficou famosa na voz de Zezé Di Camargo & Luciano.",
        "answer": "Verdade"},
    {"text": "A cidade de Fortaleza é banhada pelo Oceano Pacífico.", "answer": "Falso"},
    {"text": "O Brasil faz fronteira com todos os países da América do Sul, exceto Chile e Equador.",
     "answer": "Verdade"},
    {"text": "A humorista Tatá Werneck também é conhecida por atuar em novelas.",
        "answer": "Verdade"},
    {"text": "O estado de Pernambuco é conhecido pela dança do frevo.", "answer": "Verdade"},
    {"text": "O jogador Rogério Ceni ficou famoso por ser goleiro e marcar muitos gols.",
        "answer": "Verdade"},
    {"text": "A atriz Regina Casé é a apresentadora original do programa 'É de Casa'.", "answer": "Falso"},
    {"text": "O primeiro ciclo econômico do Brasil foi o ciclo da borracha.",
        "answer": "Falso"},
    {"text": "A Ilha de Fernando de Noronha pertence ao estado de Pernambuco.",
        "answer": "Verdade"},
    {"text": "O cantor Belo começou sua carreira no grupo Raça Negra.", "answer": "Falso"},
    {"text": "Sergipe é o menor estado brasileiro em extensão territorial.",
        "answer": "Verdade"},
    {"text": "A música 'Garota de Ipanema' é uma parceria de Tom Jobim e Vinicius de Moraes.",
        "answer": "Verdade"},
    {"text": "O rio mais extenso do Brasil é o Rio Paraná.", "answer": "Falso"},
    {"text": "A atriz Ingrid Guimarães é conhecida por seus papéis em comédias.",
        "answer": "Verdade"},
    {"text": "A moeda chamada 'cruzado' existiu no Brasil.", "answer": "Verdade"},
    {"text": "O humorista Renato Aragão foi membro do grupo Os Trapalhões.",
        "answer": "Verdade"},
    {"text": "A cajuína é uma bebida típica da região Sul do Brasil.", "answer": "Falso"},
    {"text": "A cantora Joelma ficou conhecida pela banda Calypso.", "answer": "Verdade"},
    {"text": "O estado de Mato Grosso do Sul tem como capital a cidade de Dourados.",
        "answer": "Falso"},
    {"text": "O músico Tim Maia era famoso por seu estilo irreverente e voz marcante.",
        "answer": "Verdade"},
    {"text": "O Parque Nacional dos Lençóis Maranhenses está localizado no Ceará.",
        "answer": "Falso"},
    {"text": "A influencer Virgínia Fonseca é uma das maiores criadoras de conteúdo do Brasil.",
        "answer": "Verdade"},
    {"text": "A seleção brasileira feminina de vôlei conquistou ouro em Pequim 2008.",
        "answer": "Verdade"},
    {"text": "A novela 'Terra Nostra' falava sobre imigração japonesa.", "answer": "Falso"},
    {"text": "O cantor Raul Seixas é conhecido como o 'pai do rock brasileiro'.",
        "answer": "Falso"},
    {"text": "A cidade de Gramado, no RS, é famosa pelo Festival de Cinema.",
        "answer": "Verdade"},
    {"text": "O escritor Paulo Coelho é membro da Academia Brasileira de Letras.",
        "answer": "Verdade"},
    {"text": "O maracatu é uma manifestação cultural do Sudeste.", "answer": "Falso"},
    {"text": "A atriz Giovanna Antonelli interpretou Jade em O Clone.", "answer": "Verdade"},
    {"text": "O estado do Pará é o maior produtor de açaí do Brasil.", "answer": "Verdade"},
    {"text": "The Rock já morou no Brasil quando criança.", "answer": "Falso"},
    {"text": "O jogador Zico é conhecido como 'Galinho de Quintino'.", "answer": "Verdade"},
    {"text": "A Serra da Mantiqueira atravessa três estados brasileiros.",
        "answer": "Verdade"},
    {"text": "A cantora Claudia Leitte começou sua carreira na banda Cheiro de Amor.",
        "answer": "Falso"},
    {"text": "O Brasil já teve uma princesa chamada Maria Leopoldina.", "answer": "Verdade"},
    {"text": "O ator Reynaldo Gianecchini nasceu no Rio de Janeiro.", "answer": "Falso"},
    {"text": "O Guaraná organizado em pó é uma invenção brasileira.", "answer": "Verdade"},
    {"text": "A cidade de Belém é famosa pelo Círio de Nazaré.", "answer": "Verdade"},
    {"text": "O estado do Maranhão fica na região Sudeste.", "answer": "Falso"},
    {"text": "A apresentadora Ana Furtado ficou conhecida como 'substituta oficial' da Globo.",
        "answer": "Verdade"},
    {"text": "O jogador Ronaldo Fenômeno venceu duas Copas do Mundo.", "answer": "Falso"},
    {"text": "A região Sudeste é a mais populosa do Brasil.", "answer": "Verdade"},
    {"text": "O cantor Seu Jorge é conhecido por interpretar canções de David Bowie em versão acústica.",
     "answer": "Verdade"},
    {"text": "O Brasil possui 27 unidades federativas.", "answer": "Verdade"},
    {"text": "A atriz Nanda Costa participou da novela Salve Jorge.", "answer": "Verdade"},
    {"text": "O escritor Machado de Assis foi um dos fundadores da Academia Brasileira de Letras.",
     "answer": "Verdade"},
    {"text": "O bolo de rolo é originalmente do estado do Ceará.", "answer": "Falso"},
    {"text": "A bandeira do Brasil possui exatamente quatro cores oficiais.",
        "answer": "Verdade"},
    {"text": "A seleção brasileira de vôlei masculino já foi campeã olímpica.",
        "answer": "Verdade"},
    {"text": "O Cristo Redentor foi eleito uma das Sete Maravilhas do Mundo Moderno.",
        "answer": "Verdade"},
    {"text": "Pelé marcou mais de mil gols em partidas oficiais.", "answer": "Falso"},
    {"text": "A Feijoada é um prato originalmente africano que foi adaptado no Brasil.",
        "answer": "Verdade"},
    {"text": "A inconfidência mineira ocorreu no século XVII.", "answer": "Falso"},
    {"text": "O Rio São Francisco nasce em Minas Gerais.", "answer": "Verdade"},
    {"text": "A atriz Taís Araújo foi a primeira protagonista negra de uma novela brasileira.",
        "answer": "Verdade"},
    {"text": "O Carnaval do Recife é famoso pelo desfile do Galo da Meia-Noite.",
        "answer": "Falso"},
    {"text": "A música 'Asa Branca' foi composta por Luiz Gonzaga e Humberto Teixeira.",
        "answer": "Verdade"},
    {"text": "O presidente Juscelino Kubitschek governou o Brasil durante a década de 1960.", "answer": "Falso"},
    {"text": "O açaí consumido no Norte do Brasil costuma ser salgado.",
        "answer": "Verdade"},
    {"text": "O Brasil é o maior produtor mundial de café.", "answer": "Verdade"},
    {"text": "O estado de Roraima é o único localizado totalmente acima da linha do Equador.",
        "answer": "Verdade"},
    {"text": "O Pantanal é o maior bioma brasileiro.", "answer": "Falso"},
    {"text": "A música sertaneja tem origem nas zonas rurais do Sudeste do Brasil.",
        "answer": "Verdade"},
    {"text": "O jogador Neymar começou sua carreira profissional no Santos.",
        "answer": "Verdade"},
    {"text": "O Pororoca é um fenômeno natural comum no rio Tietê.", "answer": "Falso"},
    {"text": "A atriz Fernanda Montenegro já foi indicada ao Oscar.", "answer": "Verdade"},
    {"text": "O estado do Acre foi comprado da Bolívia.", "answer": "Verdade"},
    {"text": "Lula foi o presidente mais jovem da história do Brasil.", "answer": "Falso"},
    {"text": "O Paraty é um tipo de cachaça típico do Rio Grande do Sul.", "answer": "Falso"},
    {"text": "O Santos Futebol Clube revelou jogadores como Pelé e Robinho.",
        "answer": "Verdade"},
    {"text": "A moeda brasileira já teve o nome de Cruzeiro e Cruzado.",
        "answer": "Verdade"},
    {"text": "A Serra Gaúcha é famosa pela produção de vinho.", "answer": "Verdade"},
    {"text": "A televisão chegou ao Brasil na década de 1950.", "answer": "Verdade"},
    {"text": "A canção 'Garota de Ipanema' foi escrita por Vinicius de Moraes e Tom Jobim.",
        "answer": "Verdade"},
    {"text": "O Protocolo de Kyoto foi assinado no Rio de Janeiro.", "answer": "Falso"},
    {"text": "A Amazônia é a maior floresta tropical do mundo.", "answer": "Verdade"},
    {"text": "O Rio Grande do Norte possui o maior número de praias do Brasil.",
        "answer": "Falso"},
    {"text": "O Brasil foi descoberto oficialmente em 1500.", "answer": "Verdade"},
    {"text": "A cantora Anitta iniciou a carreira no funk carioca.", "answer": "Verdade"},
    {"text": "A seleção brasileira de futebol feminino nunca participou de uma Copa do Mundo.", "answer": "Falso"},
    {"text": "O Maracanã já recebeu a final da Copa do Mundo duas vezes.",
        "answer": "Verdade"},
    {"text": "O humorista Renato Aragão fez parte do grupo Os Trapalhões.",
        "answer": "Verdade"},
    {"text": "A capital do Brasil já foi o Rio de Janeiro antes de ser Brasília.",
        "answer": "Verdade"},
    {"text": "O cantor Roberto Carlos é conhecido como o 'Rei do Pop Brasileiro'.",
        "answer": "Falso"},
    {"text": "O queijo coalho é típico da culinária nordestina.", "answer": "Verdade"},
    {"text": "A atriz Paolla Oliveira já venceu o BBB.", "answer": "Falso"},
    {"text": "O Brasil já sediou os Jogos Olímpicos.", "answer": "Verdade"},
    {"text": "O Aquífero Guarani é um dos maiores reservatórios subterrâneos de água do mundo.",
        "answer": "Verdade"},
    {"text": "A cachaça é considerada o primeiro destilado das Américas.",
        "answer": "Verdade"},
    {"text": "O cantor Caetano Veloso nasceu no Rio de Janeiro.", "answer": "Falso"},
    {"text": "A cidade de Olinda é famosa por seu Carnaval de bonecos gigantes.",
        "answer": "Verdade"},
    {"text": "O presidente Getúlio Vargas foi eleito pelo voto direto em todas as vezes que assumiu.",
     "answer": "Falso"},
    {"text": "O frevo é um ritmo típico do estado da Bahia.", "answer": "Falso"},
    {"text": "O Pão de Açúcar está localizado na cidade do Rio de Janeiro.",
        "answer": "Verdade"},
    {"text": "A apresentadora Xuxa começou a carreira como cantora infantil.",
        "answer": "Falso"},
    {"text": "O Rio de Janeiro foi a única cidade fora da Europa a ser capital de um império europeu.",
     "answer": "Verdade"},
    {"text": "A seleção brasileira feminina de vôlei nunca ganhou medalha de ouro olímpica.", "answer": "Falso"},
    {"text": "A caipirinha tradicional é feita com cachaça, limão e açúcar.",
        "answer": "Verdade"},
    {"text": "O estado de Santa Catarina é conhecido por ser o maior produtor brasileiro de soja.", "answer": "Falso"},
    {"text": "Chico Buarque é filho do historiador Sérgio Buarque de Holanda.",
        "answer": "Verdade"},
    {"text": "A primeira capital do Brasil foi Salvador.", "answer": "Verdade"},
    {"text": "A seleção brasileira de futebol ganhou cinco Copas do Mundo.",
        "answer": "Verdade"},
    {"text": "O bioma Cerrado é o menor bioma brasileiro.", "answer": "Falso"},
    {"text": "O ator Rodrigo Santoro já participou de produções de Hollywood.",
        "answer": "Verdade"},
    {"text": "O Rio Grande do Sul é o estado mais populoso do Brasil.", "answer": "Falso"},
    {"text": "A atriz Glória Pires ficou famosa por atuar no filme 'Central do Brasil'.", "answer": "Falso"},
    {"text": "Os cangaceiros foram bandos armados que atuaram no Nordeste brasileiro.",
        "answer": "Verdade"},
    {"text": "A moeda atual do Brasil, o Real, foi criada em 1994.", "answer": "Verdade"},
    {"text": "A Floresta Amazônica está presente em todos os estados da Região Norte.", "answer": "Falso"},
    {"text": "O humorista Carlos Alberto de Nóbrega apresenta o programa 'A Praça é Nossa'.",
        "answer": "Verdade"},
    {"text": "O termo 'MPB' significa Música Popular Brasileira.", "answer": "Verdade"},
    {"text": "A Guerra de Canudos ocorreu no estado do Maranhão.", "answer": "Falso"},
    {"text": "O maior porto do Brasil está localizado em Santos.", "answer": "Verdade"},
    {"text": "O escritor Monteiro Lobato criou o Sítio do Pica-Pau Amarelo.",
        "answer": "Verdade"},
    {"text": "A capital do estado do Amapá é Porto Velho.", "answer": "Falso"},
    {"text": "O Brasil já teve uma mulher presidente da República.", "answer": "Verdade"},
    {"text": "A cajuína é uma bebida típica do Ceará e Piauí.", "answer": "Verdade"},
    {"text": "O boto-cor-de-rosa é encontrado apenas na costa brasileira.", "answer": "Falso"},
    {"text": "O jogador Zico ficou conhecido como 'Galinho de Quintino'.",
        "answer": "Verdade"},
    {"text": "O Rio de Janeiro sediou a Copa do Mundo de 1950.", "answer": "Verdade"},
    {"text": "A comida típica caruru tem origem na culinária baiana.", "answer": "Verdade"},
    {"text": "A Ponte Hercílio Luz fica no estado do Rio Grande do Norte.", "answer": "Falso"},
    {"text": "O 'Cangaço' é um tema frequentemente retratado no cinema brasileiro.",
        "answer": "Verdade"},
    {"text": "A música 'Evidências' ficou famosa na voz de Chitãozinho & Xororó.",
        "answer": "Verdade"},
    {"text": "O campeonato brasileiro de futebol começou na década de 1990.",
        "answer": "Falso"},
    {"text": "A Serra do Mar está localizada apenas no estado do Rio de Janeiro.",
        "answer": "Falso"},
    {"text": "A atriz Larissa Manoela começou sua carreira atuando no SBT.",
        "answer": "Verdade"},
    {"text": "O Brasil é banhado apenas pelo Oceano Atlântico.", "answer": "Verdade"},
    {"text": "O autor Paulo Coelho é um dos escritores brasileiros mais vendidos no mundo.",
        "answer": "Verdade"},
    {"text": "O Parque Nacional dos Lençóis Maranhenses fica no estado do Pará.",
        "answer": "Falso"},
    {"text": "O cantor Tim Maia foi um dos pioneiros da soul music no Brasil.",
        "answer": "Verdade"},
    {"text": "O estado do Mato Grosso é conhecido como berço do Pantanal.",
        "answer": "Verdade"},
    {"text": "A cidade de São Paulo já foi conhecida como Piratininga.",
        "answer": "Verdade"},
    {"text": "O Brasil participou da Primeira Guerra Mundial.", "answer": "Verdade"},
    {"text": "O humorista Whindersson Nunes nasceu em São Paulo.", "answer": "Falso"},
    {"text": "A Amazônia brasileira representa mais de 50% da floresta amazônica total.",
        "answer": "Verdade"},
    {"text": "O escritor José de Alencar escreveu 'Dom Casmurro'.", "answer": "Falso"},
    {"text": "O ator Tony Ramos é conhecido por sua versatilidade e longa carreira na TV brasileira.",
     "answer": "Verdade"},
    {"text": "O principal ingrediente da tapioca é a mandioca.", "answer": "Verdade"},
    {"text": "O Rio Tietê nasce no litoral paulista.", "answer": "Falso"},
    {"text": "O estado de Pernambuco é conhecido como berço do Frevo e do Maracatu.",
        "answer": "Verdade"},
    {"text": "A Copa do Mundo de 2014 foi sediada exclusivamente em São Paulo e Rio de Janeiro.", "answer": "Falso"},
    {"text": "O cantor Belo é conhecido principalmente por seu trabalho no samba e pagode.",
        "answer": "Verdade"},
    {"text": "O prato tacacá é tradicional da culinária do Sul do Brasil.", "answer": "Falso"},
    {"text": "A atriz Maisa Silva começou a carreira no programa do Raul Gil.",
        "answer": "Verdade"}
]
